name: Release docs

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.203
    - name: Restore tools
      run: dotnet tool restore
    - name: Run Fornax
      run: dotnet run -- PublishDocs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_public
        publish_branch: gh-pages
        force_orphan: true
